import './globals.css';
import Footer from './Shared/Footer/page';
import Header from './Shared/Header/page';

// const geistSans = Geist({
//   variable: "font-",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: 'Bulipe Tech Limited',
  description: 'Generated by Bulipe Tech Limited',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-ubuntu ">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
